# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ec2-user/TLB-Commandos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ec2-user/TLB-Commandos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/TLB-Commandos/CMakeFiles /home/ec2-user/TLB-Commandos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/TLB-Commandos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bw

# Build rule for target.
bw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bw
.PHONY : bw

# fast build rule for target.
bw/fast:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/build
.PHONY : bw/fast

#=============================================================================
# Target rules for targets named measure_interval

# Build rule for target.
measure_interval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 measure_interval
.PHONY : measure_interval

# fast build rule for target.
measure_interval/fast:
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/build
.PHONY : measure_interval/fast

#=============================================================================
# Target rules for targets named measure_tlb

# Build rule for target.
measure_tlb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 measure_tlb
.PHONY : measure_tlb

# fast build rule for target.
measure_tlb/fast:
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/build
.PHONY : measure_tlb/fast

#=============================================================================
# Target rules for targets named tlb

# Build rule for target.
tlb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlb
.PHONY : tlb

# fast build rule for target.
tlb/fast:
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/build
.PHONY : tlb/fast

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/main.s
.PHONY : main.s

# target to build an object file
measure_bandwidth.o:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/measure_bandwidth.o
.PHONY : measure_bandwidth.o

# target to preprocess a source file
measure_bandwidth.i:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/measure_bandwidth.i
.PHONY : measure_bandwidth.i

# target to generate assembly for a file
measure_bandwidth.s:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/measure_bandwidth.s
.PHONY : measure_bandwidth.s

# target to build an object file
measure_interval.o:
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/measure_interval.o
.PHONY : measure_interval.o

# target to preprocess a source file
measure_interval.i:
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/measure_interval.i
.PHONY : measure_interval.i

# target to generate assembly for a file
measure_interval.s:
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/measure_interval.s
.PHONY : measure_interval.s

# target to build an object file
measure_tlb.o:
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/measure_tlb.o
.PHONY : measure_tlb.o

# target to preprocess a source file
measure_tlb.i:
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/measure_tlb.i
.PHONY : measure_tlb.i

# target to generate assembly for a file
measure_tlb.s:
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/measure_tlb.s
.PHONY : measure_tlb.s

# target to build an object file
utils.o:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/utils.o
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/utils.o
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/utils.o
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/utils.o
.PHONY : utils.o

# target to preprocess a source file
utils.i:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/utils.i
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/utils.i
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/utils.i
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/utils.i
.PHONY : utils.i

# target to generate assembly for a file
utils.s:
	$(MAKE) -f CMakeFiles/bw.dir/build.make CMakeFiles/bw.dir/utils.s
	$(MAKE) -f CMakeFiles/measure_interval.dir/build.make CMakeFiles/measure_interval.dir/utils.s
	$(MAKE) -f CMakeFiles/measure_tlb.dir/build.make CMakeFiles/measure_tlb.dir/utils.s
	$(MAKE) -f CMakeFiles/tlb.dir/build.make CMakeFiles/tlb.dir/utils.s
.PHONY : utils.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bw"
	@echo "... edit_cache"
	@echo "... measure_interval"
	@echo "... measure_tlb"
	@echo "... rebuild_cache"
	@echo "... tlb"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... measure_bandwidth.o"
	@echo "... measure_bandwidth.i"
	@echo "... measure_bandwidth.s"
	@echo "... measure_interval.o"
	@echo "... measure_interval.i"
	@echo "... measure_interval.s"
	@echo "... measure_tlb.o"
	@echo "... measure_tlb.i"
	@echo "... measure_tlb.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

